### ISSUE TITLE
Hi, How did you initialize the model weights of S3D-G?

### ISSUE THREAD

**Issue by qijiezhao** [wanjinchang/I3D_Master#1]
How did you initialize the model weights of S3D-G?

Specifically, how to initialize the weights of 1xkxk and kx1x1?

**Comment by wanjinchang** [comment]
I think this is similar with the algorithm Pseudo-3D Residual Networks, which separable the 3d convolution to spatial convolution 1xkxk and temporal convolution kx1x1.We can use TensorFlow API--tf.get_variables() to initialize the weights of them.

**Comment by wanjinchang** [comment]
I think this is similar with the algorithm Pseudo-3D Residual Networks, which separable the 3d convolution to spatial convolution 1xkxk and temporal convolution kx1x1.We can use TensorFlow API--tf.get_variable() to initialize the weights of them.

**Comment by wanjinchang** [comment]
I think this is similar with the algorithm Pseudo-3D Residual Networks, which separate the 3d convolution to spatial convolution 1xkxk and temporal convolution kx1x1.We can use TensorFlow API--tf.get_variable() to initialize the weights of them.

**Comment by qijiezhao** [comment]
If the weights do not borrow info from pretrained data(like imagenet), the convergence process would take too long time.
I mean simply initialization by distributions is not very smart fo large networks.

**Comment by wanjinchang** [comment]
Oh,I understand what you mean.Right,training Inflated 3D ConvNet model is finetuned from ImageNet model,but i didnot do this finetune.You can make https://github.com/yoosan/i3d-tensorflow/blob/master/convert_weights.py as reference to initialize your weights to train your model.
And when I train the S3D-G,I didnnot do this finetune process.

**Comment by qijiezhao** [comment]
Thanks,
Besides, there is another point. We can use 2D model pretrained on ImageNet to initialize the 1xkxk kernels. Then what about kx1x1?  I have also developed a pytorch version of S3D-G(to train on Kinetics), 1xkxk kernels directly do as above, but kx1x1 is unfixed right now. The raw paper of P3D says kx1x1 do not borrow info from anywhere. 
Untill now, no methods could make the training process faster of my S3D-G. Initialization of kx1x1 may should be solved first.
What's your opinion?

**Comment by wanjinchang** [comment]
Maybe you can try to use the kinetics-i3d pretrained model(https://github.com/deepmind/kinetics-i3d) released by facebook research.And extract the temporal weights kx1x1 by averaging the value of  kinetics-i3d pretrained model weights(kxkxk) on spatial dims to initialize your kx1x1 kernels.
What's your idea??

**Comment by wanjinchang** [comment]
Maybe you can try to use the kinetics-i3d pretrained model(https://github.com/deepmind/kinetics-i3d) released by deepmind.And extract the temporal weights kx1x1 by averaging the value of kinetics-i3d pretrained model weights(kxkxk) on spatial dims to initialize your kx1x1 kernels.
What's your idea??
